// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Data;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(ToDoListDbContext))]
    [Migration("20231001234602_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoList.Models.Item", b =>
                {
                    b.Property<string>("TaskID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TaskID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            TaskID = "q1j9rEh2Xw",
                            Category = 1,
                            CreatedBy = "john_doe",
                            Description = "Buy groceries for the week",
                            DueDate = new DateTime(2023, 9, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Buy Groceries"
                        },
                        new
                        {
                            TaskID = "s2kDfPz8Tm",
                            Category = 0,
                            CreatedBy = "jane_smith",
                            Description = "Finish the project report for the presentation",
                            DueDate = new DateTime(2023, 9, 16, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Finish Project Report"
                        },
                        new
                        {
                            TaskID = "t3mHxVz7Yn",
                            Category = 0,
                            CreatedBy = "alice_jones",
                            Description = "Attend the weekly team meeting",
                            DueDate = new DateTime(2023, 9, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Attend Team Meeting"
                        },
                        new
                        {
                            TaskID = "w4oPqRv5Au",
                            Category = 3,
                            CreatedBy = "bob_smith",
                            Description = "Plan a weekend getaway with friends",
                            DueDate = new DateTime(2023, 9, 18, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Plan Weekend Getaway"
                        },
                        new
                        {
                            TaskID = "y5uJwQb4Bv",
                            Category = 2,
                            CreatedBy = "sarah_davis",
                            Description = "Study and prepare for the upcoming exam",
                            DueDate = new DateTime(2023, 9, 19, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Prepare for Exam"
                        },
                        new
                        {
                            TaskID = "z6vKxUc3Cx",
                            Category = 1,
                            CreatedBy = "mike_adams",
                            Description = "Hit the gym for a workout session",
                            DueDate = new DateTime(2023, 9, 20, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Workout at the Gym"
                        },
                        new
                        {
                            TaskID = "x7tLrNm9Dz",
                            Category = 0,
                            CreatedBy = "admin_user",
                            Description = "Review the quarterly financial report",
                            DueDate = new DateTime(2023, 9, 21, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Review Quarterly Report"
                        },
                        new
                        {
                            TaskID = "p8qOsXe1Lf",
                            Category = 0,
                            CreatedBy = "admin_user",
                            Description = "Submit expense reports for reimbursement",
                            DueDate = new DateTime(2023, 9, 22, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Submit Expense Reports"
                        },
                        new
                        {
                            TaskID = "k9vZpMt0Ki",
                            Category = 0,
                            CreatedBy = "admin_user",
                            Description = "Plan a company retreat for team building",
                            DueDate = new DateTime(2023, 9, 23, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Plan Company Retreat"
                        },
                        new
                        {
                            TaskID = "a1bCdEf2Gh",
                            Category = 0,
                            CreatedBy = "emily_wilson",
                            Description = "Finalize and submit the project proposal",
                            DueDate = new DateTime(2023, 9, 24, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Complete Project Proposal"
                        },
                        new
                        {
                            TaskID = "b2CkLmN3Op",
                            Category = 1,
                            CreatedBy = "john_doe",
                            Description = "Give Mom a call and catch up",
                            DueDate = new DateTime(2023, 9, 25, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Call Mom"
                        },
                        new
                        {
                            TaskID = "c3DnOpQ4Rs",
                            Category = 1,
                            CreatedBy = "jane_smith",
                            Description = "Pay the electricity and water bills",
                            DueDate = new DateTime(2023, 9, 26, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Pay Utility Bills"
                        },
                        new
                        {
                            TaskID = "d4EpQrS5Tu",
                            Category = 0,
                            CreatedBy = "alice_jones",
                            Description = "Update the resume with recent achievements",
                            DueDate = new DateTime(2023, 9, 27, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Update Resume"
                        },
                        new
                        {
                            TaskID = "e5FqRsT6Vw",
                            Category = 2,
                            CreatedBy = "bob_smith",
                            Description = "Attend the online webinar on artificial intelligence",
                            DueDate = new DateTime(2023, 9, 28, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Attend Webinar on AI"
                        },
                        new
                        {
                            TaskID = "f6GsTuV7Wx",
                            Category = 0,
                            CreatedBy = "sarah_davis",
                            Description = "Write a blog post about the latest tech trends",
                            DueDate = new DateTime(2023, 9, 29, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Write Blog Post"
                        },
                        new
                        {
                            TaskID = "g7HtUvW8Xy",
                            Category = 0,
                            CreatedBy = "mike_adams",
                            Description = "Review and provide feedback on the project code",
                            DueDate = new DateTime(2023, 9, 30, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Review Code for Project"
                        },
                        new
                        {
                            TaskID = "h8IuWxY9Zz",
                            Category = 3,
                            CreatedBy = "admin_user",
                            Description = "Plan a surprise anniversary celebration",
                            DueDate = new DateTime(2023, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Plan Anniversary Celebration"
                        },
                        new
                        {
                            TaskID = "i9JvXyZ1Aa",
                            Category = 1,
                            CreatedBy = "admin_user",
                            Description = "Schedule a dental checkup appointment",
                            DueDate = new DateTime(2023, 10, 2, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Schedule Dentist Appointment"
                        },
                        new
                        {
                            TaskID = "j0KwYz1BbC",
                            Category = 3,
                            CreatedBy = "admin_user",
                            Description = "Research potential vacation destinations",
                            DueDate = new DateTime(2023, 10, 3, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Research Vacation Destinations"
                        },
                        new
                        {
                            TaskID = "k1LxZ2CcDd",
                            Category = 0,
                            CreatedBy = "emily_wilson",
                            Description = "Prepare a presentation for an upcoming meeting",
                            DueDate = new DateTime(2023, 10, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Create Presentation for Meeting"
                        },
                        new
                        {
                            TaskID = "m2NyZ3OdPe",
                            Category = 1,
                            CreatedBy = "john_doe",
                            Description = "Buy groceries for the family",
                            DueDate = new DateTime(2023, 10, 5, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Grocery Shopping"
                        },
                        new
                        {
                            TaskID = "o3PzA4QeRf",
                            Category = 1,
                            CreatedBy = "jane_smith",
                            Description = "Make a payment for the credit card bill",
                            DueDate = new DateTime(2023, 10, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Pay Credit Card Bill"
                        },
                        new
                        {
                            TaskID = "q4RsT5UfSg",
                            Category = 0,
                            CreatedBy = "alice_jones",
                            Description = "Prepare a report on current market trends",
                            DueDate = new DateTime(2023, 10, 7, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Write Report on Market Trends"
                        },
                        new
                        {
                            TaskID = "s5TuV6WgXh",
                            Category = 1,
                            CreatedBy = "bob_smith",
                            Description = "Take the dog for a walk in the park",
                            DueDate = new DateTime(2023, 10, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Walk the Dog"
                        },
                        new
                        {
                            TaskID = "u6VwXyZiAj",
                            Category = 3,
                            CreatedBy = "sarah_davis",
                            Description = "Book flight tickets for the upcoming vacation",
                            DueDate = new DateTime(2023, 10, 9, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Book Flight Tickets"
                        },
                        new
                        {
                            TaskID = "w7XyZ1AkBl",
                            Category = 2,
                            CreatedBy = "mike_adams",
                            Description = "Attend the coding bootcamp workshop",
                            DueDate = new DateTime(2023, 10, 10, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Attend Coding Bootcamp"
                        },
                        new
                        {
                            TaskID = "z8Z1AaBmCn",
                            Category = 3,
                            CreatedBy = "admin_user",
                            Description = "Plan a surprise anniversary celebration",
                            DueDate = new DateTime(2023, 10, 11, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Title = "Plan Anniversary Celebration"
                        },
                        new
                        {
                            TaskID = "A9bBmCnDoE",
                            Category = 1,
                            CreatedBy = "admin_user",
                            Description = "Pay the monthly rent for the apartment",
                            DueDate = new DateTime(2023, 10, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Pay Rent"
                        },
                        new
                        {
                            TaskID = "B0cDnEoFpG",
                            Category = 0,
                            CreatedBy = "admin_user",
                            Description = "Research and compare new tech gadgets",
                            DueDate = new DateTime(2023, 10, 13, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Title = "Research New Tech Gadgets"
                        });
                });

            modelBuilder.Entity("ToDoList.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
